### PR TITLE
Revert "Update Authorization to return state"

### PR DESCRIPTION
**Pull request by wusgarden**
Reverts apifest/apifest-oauth20#87

### CODE REVIEW

**Comment by rossitsaborissova** [comment]
Why did you revert the change?

**Comment by wusgarden** [comment]
My unit tests were breaking t

**Comment by rossitsaborissova** [comment]
Yes, because of missing "=" after clientId.
I have just found it out as I saw they are failing.

**Comment by wusgarden** [comment]
I'll close this revert then.  Sorry for the confusion

**Comment by rossitsaborissova** [comment]
Can you please use "[Issue #89 ] Add state in authorization code response" as a commit message? I've logged an issue for that fix.

**Comment by rossitsaborissova** [comment]
I merged the fix, otherwise the build was failing. Thanks for your contribution !

**Pull request closed without merging**
